services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-nexus
    container_name: backend-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=nexus
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=super_secret_token
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    entrypoint: /app/entrypoint.sh

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-nexus
    container_name: frontend-app
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexus
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata: